### ISSUE TITLE
Templates "How to use?"

### ISSUE THREAD

**Issue by vkosmirak** [tomkowz/NetworkLayerExample#5]
Could you please describe somewhere how to use your network templates?

**Comment by SpacyRicochet** [comment]
Xcode has a `Templates` directory where you can find both File Templates and Project Templates. In either of those, you can create a new Directory to make a new template category and add the `.xctemplate` there.

```/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Xcode/Templates/```

For example, creating (from the above path) `./File Templates/Test/Playground.xctemplate` will result in this;

![screen shot 2017-03-10 at 15 10 22](https://cloud.githubusercontent.com/assets/904596/23798202/c6f6b79e-05a3-11e7-9df9-b6bb2b1c77d9.png)
